// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Wj58MiEnPP9BFIwcwAA4mfNsAJatD8s',
    appId: '1:741435443869:android:87d60b40e273e14a61e274',
    messagingSenderId: '741435443869',
    projectId: 'sustainable-living-guide-b77d1',
    storageBucket: 'sustainable-living-guide-b77d1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBIv9hEDXbSieunidAgUfbdCCd7WlCP1o',
    appId: '1:741435443869:ios:f076cd1624089dd161e274',
    messagingSenderId: '741435443869',
    projectId: 'sustainable-living-guide-b77d1',
    storageBucket: 'sustainable-living-guide-b77d1.firebasestorage.app',
    iosBundleId: 'com.nsikak.sustainablelivingguide',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAHh4mfnuWbF6FTrmmXuSYfLykmXhpDrA',
    appId: '1:741435443869:web:11e5d30e52154e1361e274',
    messagingSenderId: '741435443869',
    projectId: 'sustainable-living-guide-b77d1',
    authDomain: 'sustainable-living-guide-b77d1.firebaseapp.com',
    storageBucket: 'sustainable-living-guide-b77d1.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBIv9hEDXbSieunidAgUfbdCCd7WlCP1o',
    appId: '1:741435443869:ios:ff5423093d57b07b61e274',
    messagingSenderId: '741435443869',
    projectId: 'sustainable-living-guide-b77d1',
    storageBucket: 'sustainable-living-guide-b77d1.firebasestorage.app',
    iosBundleId: 'com.nsikak.sustainableLivingGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAHh4mfnuWbF6FTrmmXuSYfLykmXhpDrA',
    appId: '1:741435443869:web:271371599dc7e42161e274',
    messagingSenderId: '741435443869',
    projectId: 'sustainable-living-guide-b77d1',
    authDomain: 'sustainable-living-guide-b77d1.firebaseapp.com',
    storageBucket: 'sustainable-living-guide-b77d1.firebasestorage.app',
  );
}
