import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'features/auth/provider/auth_form_provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'firebase_options.dart'; // generated by flutterfire configure, or manually set up
import 'features/auth/provider/auth_state_provider.dart';
import 'features/auth/view/login_screen.dart';
import 'features/carbon_tracker/view/carbon_tracker_screen.dart';
import 'features/eco_products/view/eco_products_screen.dart';
import 'features/challenges/view/challenges_screen.dart';
import 'features/waste_tracker/view/waste_tracker_screen.dart';
import 'features/certifications/view/certifications_screen.dart';
import 'features/recipes/view/recipes_screen.dart';
import 'features/energy_tips/view/energy_tips_screen.dart';
import 'features/travel_tips/view/travel_tips_screen.dart';
import 'features/community/view/community_screen.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'features/education/view/education_screen.dart';


Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Load environment variables from .env
  await dotenv.load(fileName: '.env');

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  await Supabase.initialize(
    url: dotenv.env['SUPABASE_URL']!,
    anonKey: dotenv.env['SUPABASE_ANON_KEY']!,
  );

  runApp(
    const ProviderScope(
      child: SustainableLivingApp(),
    ),
  );
}

class SustainableLivingApp extends StatelessWidget {
  const SustainableLivingApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sustainable Living Guide',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: const Color(0xFF0B2B13),
        scaffoldBackgroundColor: const Color(0xFFF5F4EF),
        fontFamily: null, // default Flutter font, per your decision
      ),
      home: const AuthGate(),
    );
  }
}

/// Root-level widget that decides what to show based on auth state:
/// - Loading: a splash/loading indicator while Firebase checks the session
/// - Logged in: the app's home screen
/// - Logged out: the Login screen
class AuthGate extends ConsumerWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final authState = ref.watch(authStateProvider);

    return authState.when(
      data: (user) {
        if (user != null) {
          // TODO: Replace with the real Home screen once that feature is built.
          return const _PlaceholderHomeScreen();
        }
        return const LoginScreen();
      },
      loading: () => const Scaffold(
        backgroundColor: Color(0xFFF5F4EF),
        body: Center(child: CircularProgressIndicator()),
      ),
      error: (error, stackTrace) => Scaffold(
        backgroundColor: const Color(0xFFF5F4EF),
        body: Center(child: Text('Something went wrong: $error')),
      ),
    );
  }
}

/// Temporary placeholder so we can verify the auth flow works end-to-end.
/// This will be deleted once Feature 2 (Home) is built.
class _PlaceholderHomeScreen extends ConsumerWidget {
  const _PlaceholderHomeScreen();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      backgroundColor: const Color(0xFFF5F4EF),
      appBar: AppBar(
        backgroundColor: const Color(0xFFF5F4EF),
        elevation: 0,
        title: const Text('Home (placeholder)'),
      ),
      body: Center(
  child: Column(
    mainAxisAlignment: MainAxisAlignment.center,
    children: [
      ElevatedButton(
        onPressed: () {
          Navigator.of(context).push(
            MaterialPageRoute(builder: (_) => const CarbonTrackerScreen()),
          );
        },
        child: const Text('Open Carbon Tracker'),
      ),
      const SizedBox(height: 16),
      ElevatedButton(
        onPressed: () async {
          await ref.read(authFormControllerProvider.notifier).logout();
        },
        child: const Text('Log out'),
      ),
      ElevatedButton(
        onPressed: () {
          Navigator.of(context).push(MaterialPageRoute(builder: (_) => const EcoProductsScreen()));
        }, 
        child: const Text('Open Eco Products'),
      ),
      const SizedBox(height: 16),

      ElevatedButton(
        onPressed: (){
          Navigator.of(context).push(MaterialPageRoute(builder: (_) => ChallengesScreen()));
        }, 
        child: const Text('Open Challenges')
      ),

      ElevatedButton(
        onPressed: () {
          Navigator.of(context).push(
            MaterialPageRoute(builder: (_) => const WasteTrackerScreen()),
          );
        },
        child: const Text('Open Waste Tracker'),
      ),

    ElevatedButton(
      onPressed: () {
        Navigator.of(context).push(
          MaterialPageRoute(builder: (_) => const CertificationsScreen()),
        );
      },
      child: const Text('Open Certifications Guide'),
    ),

    ElevatedButton(
       onPressed: () {
        Navigator.of(context).push(
          MaterialPageRoute(builder: (_) => const RecipesScreen()),
        );
      },
      child: const Text('Open Recipes'),
      ),

      ElevatedButton(
        onPressed: () {
          Navigator.of(context).push(
            MaterialPageRoute(builder: (_) => const EnergyTipsScreen()),
          );
        },
        child: const Text('Open Energy Tips'),
      ),

      ElevatedButton(
        onPressed: () {
          Navigator.of(context).push(
            MaterialPageRoute(builder: (_) => const TravelTipsScreen()),
          );
        },
          child: const Text('Open Travel Tips'),
      ),
      const SizedBox(height: 16),
      ElevatedButton(
  onPressed: () {
    Navigator.of(context).push(
      MaterialPageRoute(builder: (_) => const CommunityScreen()),
    );
  },
  child: const Text('Open Community'),
  ),
const SizedBox(height: 16),
const SizedBox(height: 12),
ElevatedButton(
  onPressed: () => Navigator.push(
    context,
    MaterialPageRoute(builder: (_) => const EducationScreen()),
  ),
  child: const Text('Open Educational Content'),
),
      
    ],
  ),
),
    );
  }
}